"""Add ContractUpdate model

Revision ID: 8fa7e3baf38b
Revises: 003_add_365_days
Create Date: 2026-01-07 07:12:34.343122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fa7e3baf38b'
down_revision = '003_add_365_days'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending_review', 'returned', 'updated', 'completed', name='contractupdatestatus'), nullable=False),
    sa.Column('response_provided_by_user_id', sa.Integer(), nullable=True),
    sa.Column('response_date', sa.DateTime(), nullable=True),
    sa.Column('has_document', sa.Boolean(), nullable=True),
    sa.Column('admin_comments', sa.Text(), nullable=True),
    sa.Column('returned_reason', sa.Text(), nullable=True),
    sa.Column('returned_date', sa.DateTime(), nullable=True),
    sa.Column('previous_update_id', sa.Integer(), nullable=True),
    sa.Column('correction_date', sa.DateTime(), nullable=True),
    sa.Column('initial_vendor_name', sa.String(length=255), nullable=True),
    sa.Column('initial_contract_type', sa.String(length=100), nullable=True),
    sa.Column('initial_description', sa.Text(), nullable=True),
    sa.Column('initial_expiration_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['previous_update_id'], ['contract_updates.id'], ),
    sa.ForeignKeyConstraint(['response_provided_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_updates_id'), 'contract_updates', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contract_updates_id'), table_name='contract_updates')
    op.drop_table('contract_updates')
    # ### end Alembic commands ###