"""Create vendor tables

Revision ID: 7e1a4d99fe6c
Revises: 
Create Date: 2025-08-31 13:14:20.463708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e1a4d99fe6c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.String(length=10), nullable=False),
    sa.Column('vendor_name', sa.String(length=255), nullable=False),
    sa.Column('vendor_contact_person', sa.String(length=255), nullable=False),
    sa.Column('vendor_country', sa.String(length=100), nullable=False),
    sa.Column('material_outsourcing_arrangement', sa.Enum('YES', 'NO', name='materialoutsourcingtype'), nullable=False),
    sa.Column('bank_customer', sa.Enum('ARUBA_BANK', 'ORCO_BANK', 'NONE', name='bankcustomertype'), nullable=False),
    sa.Column('cif', sa.String(length=6), nullable=True),
    sa.Column('due_diligence_required', sa.Enum('YES', 'NO', name='duediligencerequiredtype'), nullable=False),
    sa.Column('last_due_diligence_date', sa.DateTime(), nullable=True),
    sa.Column('next_required_due_diligence_date', sa.DateTime(), nullable=True),
    sa.Column('next_required_due_diligence_alert_frequency', sa.Enum('FIFTEEN_DAYS', 'THIRTY_DAYS', 'SIXTY_DAYS', 'NINETY_DAYS', 'ONE_TWENTY_DAYS', name='alertfrequencytype'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_id'), 'vendors', ['id'], unique=False)
    op.create_index(op.f('ix_vendors_vendor_id'), 'vendors', ['vendor_id'], unique=True)
    op.create_table('vendor_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_addresses_id'), 'vendor_addresses', ['id'], unique=False)
    op.create_table('vendor_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.Enum('DUE_DILIGENCE', 'NON_DISCLOSURE_AGREEMENT', 'INTEGRITY_POLICY', 'RISK_ASSESSMENT_FORM', 'BUSINESS_CONTINUITY_PLAN', 'DISASTER_RECOVERY_PLAN', 'INSURANCE_POLICY', name='documenttype'), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('custom_document_name', sa.String(length=255), nullable=False),
    sa.Column('document_signed_date', sa.DateTime(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_documents_id'), 'vendor_documents', ['id'], unique=False)
    op.create_table('vendor_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_emails_id'), 'vendor_emails', ['id'], unique=False)
    op.create_table('vendor_phones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('area_code', sa.String(length=10), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_phones_id'), 'vendor_phones', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendor_phones_id'), table_name='vendor_phones')
    op.drop_table('vendor_phones')
    op.drop_index(op.f('ix_vendor_emails_id'), table_name='vendor_emails')
    op.drop_table('vendor_emails')
    op.drop_index(op.f('ix_vendor_documents_id'), table_name='vendor_documents')
    op.drop_table('vendor_documents')
    op.drop_index(op.f('ix_vendor_addresses_id'), table_name='vendor_addresses')
    op.drop_table('vendor_addresses')
    op.drop_index(op.f('ix_vendors_vendor_id'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_id'), table_name='vendors')
    op.drop_table('vendors')
    # ### end Alembic commands ###